# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/constraints.xdc

# Block Designs: bd/sfp28/sfp28.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28 || ORIG_REF_NAME==sfp28} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_axi_dma_0_0/sfp28_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_axi_dma_0_0 || ORIG_REF_NAME==sfp28_axi_dma_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_axi_intc_0_0/sfp28_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_axi_intc_0_0 || ORIG_REF_NAME==sfp28_axi_intc_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_axi_smc_0/sfp28_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_axi_smc_0 || ORIG_REF_NAME==sfp28_axi_smc_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_cmac_usplus_0_0/sfp28_cmac_usplus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_cmac_usplus_0_0 || ORIG_REF_NAME==sfp28_cmac_usplus_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_xbar_0/sfp28_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_xbar_0 || ORIG_REF_NAME==sfp28_xbar_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_auto_ds_0/sfp28_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_auto_ds_0 || ORIG_REF_NAME==sfp28_auto_ds_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_auto_pc_0/sfp28_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_auto_pc_0 || ORIG_REF_NAME==sfp28_auto_pc_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_auto_ds_1/sfp28_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_auto_ds_1 || ORIG_REF_NAME==sfp28_auto_ds_1} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_auto_pc_1/sfp28_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_auto_pc_1 || ORIG_REF_NAME==sfp28_auto_pc_1} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_ps8_0_axi_periph_0/sfp28_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_ps8_0_axi_periph_0 || ORIG_REF_NAME==sfp28_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_rst_ps8_0_99M_0/sfp28_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_rst_ps8_0_99M_0 || ORIG_REF_NAME==sfp28_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_rx_fifo_0/sfp28_rx_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_rx_fifo_0 || ORIG_REF_NAME==sfp28_rx_fifo_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_system_ila_0_0/sfp28_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_system_ila_0_0 || ORIG_REF_NAME==sfp28_system_ila_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_system_ila_1_0/sfp28_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_system_ila_1_0 || ORIG_REF_NAME==sfp28_system_ila_1_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_system_ila_2_0/sfp28_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_system_ila_2_0 || ORIG_REF_NAME==sfp28_system_ila_2_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_tx_fifo_0/sfp28_tx_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_tx_fifo_0 || ORIG_REF_NAME==sfp28_tx_fifo_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_util_vector_logic1_0/sfp28_util_vector_logic1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_util_vector_logic1_0 || ORIG_REF_NAME==sfp28_util_vector_logic1_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_vio_0_0/sfp28_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_vio_0_0 || ORIG_REF_NAME==sfp28_vio_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_vio_1_0/sfp28_vio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_vio_1_0 || ORIG_REF_NAME==sfp28_vio_1_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_vio_2_0/sfp28_vio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_vio_2_0 || ORIG_REF_NAME==sfp28_vio_2_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_xlconcat_0_0/sfp28_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_xlconcat_0_0 || ORIG_REF_NAME==sfp28_xlconcat_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_xlconstant_0_0/sfp28_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_xlconstant_0_0 || ORIG_REF_NAME==sfp28_xlconstant_0_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_xlconstant_1_0/sfp28_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_xlconstant_1_0 || ORIG_REF_NAME==sfp28_xlconstant_1_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_xlconstant_2_0/sfp28_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_xlconstant_2_0 || ORIG_REF_NAME==sfp28_xlconstant_2_0} -quiet] -quiet

# IP: bd/sfp28/ip/sfp28_zynq_ultra_ps_e_0_0/sfp28_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sfp28_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/sfp28_ooc.xdc
