# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/sfp28_system_ila_2_0.xci
# IP: The module: 'sfp28_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/bd_cbf1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1 || ORIG_REF_NAME==bd_cbf1} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/bd_cbf1_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_1/bd_cbf1_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_g_inst_0 || ORIG_REF_NAME==bd_cbf1_g_inst_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_2/bd_cbf1_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_aw_0 || ORIG_REF_NAME==bd_cbf1_slot_0_aw_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_3/bd_cbf1_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_w_0 || ORIG_REF_NAME==bd_cbf1_slot_0_w_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_4/bd_cbf1_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_b_0 || ORIG_REF_NAME==bd_cbf1_slot_0_b_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_5/bd_cbf1_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_ar_0 || ORIG_REF_NAME==bd_cbf1_slot_0_ar_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_6/bd_cbf1_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_r_0 || ORIG_REF_NAME==bd_cbf1_slot_0_r_0} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/bd_cbf1_ila_lib_0_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/bd_cbf1_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/sfp28_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/sfp28_system_ila_2_0.xci
# IP: The module: 'sfp28_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/bd_cbf1.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1 || ORIG_REF_NAME==bd_cbf1} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/bd_cbf1_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_1/bd_cbf1_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_g_inst_0 || ORIG_REF_NAME==bd_cbf1_g_inst_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_2/bd_cbf1_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_aw_0 || ORIG_REF_NAME==bd_cbf1_slot_0_aw_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_3/bd_cbf1_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_w_0 || ORIG_REF_NAME==bd_cbf1_slot_0_w_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_4/bd_cbf1_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_b_0 || ORIG_REF_NAME==bd_cbf1_slot_0_b_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_5/bd_cbf1_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_ar_0 || ORIG_REF_NAME==bd_cbf1_slot_0_ar_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_6/bd_cbf1_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cbf1_slot_0_r_0 || ORIG_REF_NAME==bd_cbf1_slot_0_r_0} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cbf1_ila_lib_0 || ORIG_REF_NAME==bd_cbf1_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/ip/ip_0/bd_cbf1_ila_lib_0_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/bd_0/bd_cbf1_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_2_0/sfp28_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
