# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/constraints.xdc

# Block Designs: bd/qsfp2/qsfp2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2 || ORIG_REF_NAME==qsfp2} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_axi_dma_0_0/qsfp2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_axi_dma_0_0 || ORIG_REF_NAME==qsfp2_axi_dma_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_axi_intc_0_0/qsfp2_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_axi_intc_0_0 || ORIG_REF_NAME==qsfp2_axi_intc_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_axi_smc_0/qsfp2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_axi_smc_0 || ORIG_REF_NAME==qsfp2_axi_smc_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/qsfp2_cmac_usplus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_cmac_usplus_0_0 || ORIG_REF_NAME==qsfp2_cmac_usplus_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_xbar_0/qsfp2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_xbar_0 || ORIG_REF_NAME==qsfp2_xbar_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_ps8_0_axi_periph_0/qsfp2_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_ps8_0_axi_periph_0 || ORIG_REF_NAME==qsfp2_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_rst_ps8_0_99M_0/qsfp2_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_rst_ps8_0_99M_0 || ORIG_REF_NAME==qsfp2_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_rx_fifo_0/qsfp2_rx_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_rx_fifo_0 || ORIG_REF_NAME==qsfp2_rx_fifo_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_system_ila_0_0/qsfp2_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_system_ila_0_0 || ORIG_REF_NAME==qsfp2_system_ila_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_system_ila_1_0/qsfp2_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_system_ila_1_0 || ORIG_REF_NAME==qsfp2_system_ila_1_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_system_ila_2_0/qsfp2_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_system_ila_2_0 || ORIG_REF_NAME==qsfp2_system_ila_2_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_tx_fifo_0/qsfp2_tx_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_tx_fifo_0 || ORIG_REF_NAME==qsfp2_tx_fifo_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_util_vector_logic1_0/qsfp2_util_vector_logic1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_util_vector_logic1_0 || ORIG_REF_NAME==qsfp2_util_vector_logic1_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_vio_0_0/qsfp2_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_vio_0_0 || ORIG_REF_NAME==qsfp2_vio_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_vio_1_0/qsfp2_vio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_vio_1_0 || ORIG_REF_NAME==qsfp2_vio_1_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_vio_2_0/qsfp2_vio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_vio_2_0 || ORIG_REF_NAME==qsfp2_vio_2_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_xlconcat_0_0/qsfp2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_xlconcat_0_0 || ORIG_REF_NAME==qsfp2_xlconcat_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_xlconstant_0_0/qsfp2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_xlconstant_0_0 || ORIG_REF_NAME==qsfp2_xlconstant_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_xlconstant_1_0/qsfp2_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_xlconstant_1_0 || ORIG_REF_NAME==qsfp2_xlconstant_1_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_xlconstant_2_0/qsfp2_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_xlconstant_2_0 || ORIG_REF_NAME==qsfp2_xlconstant_2_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_zynq_ultra_ps_e_0_0/qsfp2_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==qsfp2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_auto_ds_0/qsfp2_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_auto_ds_0 || ORIG_REF_NAME==qsfp2_auto_ds_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_auto_pc_0/qsfp2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_auto_pc_0 || ORIG_REF_NAME==qsfp2_auto_pc_0} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_auto_ds_1/qsfp2_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_auto_ds_1 || ORIG_REF_NAME==qsfp2_auto_ds_1} -quiet] -quiet

# IP: bd/qsfp2/ip/qsfp2_auto_pc_1/qsfp2_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_auto_pc_1 || ORIG_REF_NAME==qsfp2_auto_pc_1} -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/qsfp2_ooc.xdc
