# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/qsfp2_system_ila_0_0.xci
# IP: The module: 'qsfp2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/bd_b9d3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3 || ORIG_REF_NAME==bd_b9d3} -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/bd_b9d3_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_1/bd_b9d3_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3_g_inst_0 || ORIG_REF_NAME==bd_b9d3_g_inst_0} -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/bd_b9d3_ila_lib_0_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/bd_b9d3_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/qsfp2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/qsfp2_system_ila_0_0.xci
# IP: The module: 'qsfp2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/bd_b9d3.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3 || ORIG_REF_NAME==bd_b9d3} -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/bd_b9d3_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_1/bd_b9d3_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b9d3_g_inst_0 || ORIG_REF_NAME==bd_b9d3_g_inst_0} -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b9d3_ila_lib_0 || ORIG_REF_NAME==bd_b9d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/ip/ip_0/bd_b9d3_ila_lib_0_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/bd_0/bd_b9d3_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_system_ila_0_0/qsfp2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
