# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/sfp28_system_ila_1_0.xci
# IP: The module: 'sfp28_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/bd_cb01.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01 || ORIG_REF_NAME==bd_cb01} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/bd_cb01_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_1/bd_cb01_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01_g_inst_0 || ORIG_REF_NAME==bd_cb01_g_inst_0} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/bd_cb01_ila_lib_0_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/bd_cb01_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/sfp28_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/sfp28_system_ila_1_0.xci
# IP: The module: 'sfp28_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/bd_cb01.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01 || ORIG_REF_NAME==bd_cb01} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/bd_cb01_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_1/bd_cb01_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cb01_g_inst_0 || ORIG_REF_NAME==bd_cb01_g_inst_0} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb01_ila_lib_0 || ORIG_REF_NAME==bd_cb01_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/ip/ip_0/bd_cb01_ila_lib_0_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/bd_0/bd_cb01_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_system_ila_1_0/sfp28_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
