# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/sfp28_cmac_usplus_0_0.xci
# IP: The module: 'sfp28_cmac_usplus_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/sfp28_cmac_usplus_0_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_cmac_usplus_0_0_gt || ORIG_REF_NAME==sfp28_cmac_usplus_0_0_gt} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/synth/sfp28_cmac_usplus_0_0_gt_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/synth/sfp28_cmac_usplus_0_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sfp28_cmac_usplus_0_0_gt || ORIG_REF_NAME==sfp28_cmac_usplus_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.srcs/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/sfp28_cmac_usplus_0_0.xci
# IP: The module: 'sfp28_cmac_usplus_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/sfp28_cmac_usplus_0_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfp28_cmac_usplus_0_0_gt || ORIG_REF_NAME==sfp28_cmac_usplus_0_0_gt} -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/synth/sfp28_cmac_usplus_0_0_gt_ooc.xdc

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/ip_0/synth/sfp28_cmac_usplus_0_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sfp28_cmac_usplus_0_0_gt || ORIG_REF_NAME==sfp28_cmac_usplus_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Kaos_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_SFP28/CMAC_SFP28.gen/sources_1/bd/sfp28/ip/sfp28_cmac_usplus_0_0/synth/sfp28_cmac_usplus_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfp28_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
