# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/qsfp2_cmac_usplus_0_0.xci
# IP: The module: 'qsfp2_cmac_usplus_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/qsfp2_cmac_usplus_0_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_cmac_usplus_0_0_gt || ORIG_REF_NAME==qsfp2_cmac_usplus_0_0_gt} -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/synth/qsfp2_cmac_usplus_0_0_gt_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/synth/qsfp2_cmac_usplus_0_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qsfp2_cmac_usplus_0_0_gt || ORIG_REF_NAME==qsfp2_cmac_usplus_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/qsfp2_cmac_usplus_0_0.xci
# IP: The module: 'qsfp2_cmac_usplus_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/qsfp2_cmac_usplus_0_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qsfp2_cmac_usplus_0_0_gt || ORIG_REF_NAME==qsfp2_cmac_usplus_0_0_gt} -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/synth/qsfp2_cmac_usplus_0_0_gt_ooc.xdc

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/ip_0/synth/qsfp2_cmac_usplus_0_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qsfp2_cmac_usplus_0_0_gt || ORIG_REF_NAME==qsfp2_cmac_usplus_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_cmac_usplus_0_0/synth/qsfp2_cmac_usplus_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_cmac_usplus_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
