# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_auto_pc_1/qsfp2_auto_pc_1.xci
# IP: The module: 'qsfp2_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_auto_pc_1/qsfp2_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.srcs/sources_1/bd/qsfp2/ip/qsfp2_auto_pc_1/qsfp2_auto_pc_1.xci
# IP: The module: 'qsfp2_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/KaOs_Tech/GitHub/100GBE-PYNQ/ZCU111/vivado/CMAC_Aldec_QSFP2/CMAC_Aldec_QSFP2.gen/sources_1/bd/qsfp2/ip/qsfp2_auto_pc_1/qsfp2_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qsfp2_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
